language: cpp
compiler: gcc
sudo: true

before_install:
  # C++14
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  # SFML
  - sudo apt-add-repository ppa:sonkun/sfml-development -y
  - sudo apt-get update -qq
  # Codecov
  - sudo pip install codecov

install: 
  # C++14
  - sudo apt-get install -qq g++-5  
  # SFML
  - sudo apt-get install libsfml-dev
  # Codecov
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 90

script: 
  - qmake
  - make
  - ./travis_qmake_gcc_cpp14_gcov_sfml
  # Codecov
  - ./get_code_cov.sh
  - codecov

after_success:
  # Codecov
  - bash <(curl -s https://codecov.io/bash)
